FROM debian:bullseye

RUN apt-get update && apt-get install -y nginx

COPY default /etc/nginx/sites-enabled/default

COPY docker-entrypoint.sh /docker-entrypoint.sh

RUN chmod +x /docker-entrypoint.sh

EXPOSE 80
